### PR TITLE
andyrozman changes to HidManager and HidServices, added scanInterval as parameters

### PR DESCRIPTION
**Pull request by andyrozman**

### CODE REVIEW

**Comment by andyrozman** [comment]
This are minor changes to HidManager and HidServices:
- HidManager - added methods for scanInterval and autoShutdown
- HidServices - added static parameter for scanInterval

**Comment by leif81** [comment]
Lots of whitespace changes. Is it possible to undo those? It's tricky to view the diff with ask that noise.

**Comment by gary-rowe** [comment]
Thanks for this pull request, would you mind reformatting into the style as hid4java (Java Standard with 2 spaces) to assist code review?

**Comment by gary-rowe** [comment]
@andyrozman Any chance you could update the PR with the latest `develop` branch and adjust whitespace?

**Comment by gary-rowe** [comment]
@andyrozman Can we work together on this in the coming weeks to bring in your changes for 0.6.0?

**Comment by andyrozman** [comment]
@gary-rowe . I am currently on vacation and my computer access is quite limited. I am back on 22, and we can do this then. Do you have perhaps formatting rules you use, so that I could import it into your project on my computer. I use standard 4 spaces formatting, which is probably not the case in your project.

**Comment by gary-rowe** [comment]
@andyrozman For the hid4java project I use 2 spaces formatting. Happy to wait until you're back and settled to work on it. Enjoy your time off :-)

**Comment by gary-rowe** [comment]
I'll close this one now given that it's been some time.

**Pull request closed without merging**
